In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.svm import SVC
import statsmodels.api as sm
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier, plot_tree

## Data Cleaning

In [2]:
countywithnames = pd.read_csv("county_facts.csv")

In [3]:
countywithnames.dropna(inplace=True)

In [4]:
county_facts = countywithnames.set_index("fips")

In [5]:
county_facts

,area_name,state_abbreviation,PST045214,PST040210,PST120214,POP010210,AGE135214,AGE295214,AGE775214,SEX255214,...,SBO415207,SBO015207,MAN450207,WTN220207,RTN130207,RTN131207,AFN120207,BPS030214,LND110210,POP060210
fips,,,,,,,,,,,,,,,,,,,,,
1001,Autauga County,AL,55395,54571,1.5,54571,6.0,25.2,13.8,51.4,...,0.7,31.7,0,0,598175,12003,88157,131,594.44,91.8
1003,Baldwin County,AL,200111,182265,9.8,182265,5.6,22.2,18.7,51.2,...,1.3,27.3,1410273,0,2966489,17166,436955,1384,1589.78,114.6
1005,Barbour County,AL,26887,27457,-2.1,27457,5.7,21.2,16.5,46.6,...,0.0,27.0,0,0,188337,6334,0,8,884.88,31.0
1007,Bibb County,AL,22506,22919,-1.8,22915,5.3,21.0,14.8,45.9,...,0.0,0.0,0,0,124707,5804,10757,19,622.58,36.8
1009,Blount County,AL,57719,57322,0.7,57322,6.1,23.6,17.0,50.5,...,0.0,23.2,341544,0,319700,5622,20941,3,644.78,88.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56037,Sweetwater County,WY,45010,43806,2.7,43806,7.3,27.0,9.5,48.1,...,3.8,27.2,0,437493,898189,22843,150439,227,10426.65,4.2
56039,Teton County,WY,22930,21294,7.7,21294,5.7,19.1,12.2,48.2,...,3.3,25.3,0,0,515644,25688,327363,145,3995.38,5.3
56041,Uinta County,WY,20904,21118,-1.0,21118,7.6,29.8,11.0,49.6,...,2.2,15.9,0,159375,413983,20626,35497,40,2081.26,10.1
56043,Washakie County,WY,8322,8533,-2.5,8533,5.5,23.9,20.1,49.3,...,0.0,26.9,0,12128,98308,12596,10175,4,2238.55,3.8
56045,Weston County,WY,7201,7208,-0.1,7208,6.5,21.6,18.1,47.4,...,0.0,29.3,0,11540,64312,9395,7520,1,2398.09,3.0

In [6]:
facts_used = county_facts.drop(['area_name', 'state_abbreviation'], axis = 1)

In [7]:
facts_used

,PST045214,PST040210,PST120214,POP010210,AGE135214,AGE295214,AGE775214,SEX255214,RHI125214,RHI225214,...,SBO415207,SBO015207,MAN450207,WTN220207,RTN130207,RTN131207,AFN120207,BPS030214,LND110210,POP060210
fips,,,,,,,,,,,,,,,,,,,,,
1001,55395,54571,1.5,54571,6.0,25.2,13.8,51.4,77.9,18.7,...,0.7,31.7,0,0,598175,12003,88157,131,594.44,91.8
1003,200111,182265,9.8,182265,5.6,22.2,18.7,51.2,87.1,9.6,...,1.3,27.3,1410273,0,2966489,17166,436955,1384,1589.78,114.6
1005,26887,27457,-2.1,27457,5.7,21.2,16.5,46.6,50.2,47.6,...,0.0,27.0,0,0,188337,6334,0,8,884.88,31.0
1007,22506,22919,-1.8,22915,5.3,21.0,14.8,45.9,76.3,22.1,...,0.0,0.0,0,0,124707,5804,10757,19,622.58,36.8
1009,57719,57322,0.7,57322,6.1,23.6,17.0,50.5,96.0,1.8,...,0.0,23.2,341544,0,319700,5622,20941,3,644.78,88.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56037,45010,43806,2.7,43806,7.3,27.0,9.5,48.1,94.3,1.5,...,3.8,27.2,0,437493,898189,22843,150439,227,10426.65,4.2
56039,22930,21294,7.7,21294,5.7,19.1,12.2,48.2,94.9,1.2,...,3.3,25.3,0,0,515644,25688,327363,145,3995.38,5.3
56041,20904,21118,-1.0,21118,7.6,29.8,11.0,49.6,95.4,0.9,...,2.2,15.9,0,159375,413983,20626,35497,40,2081.26,10.1
56043,8322,8533,-2.5,8533,5.5,23.9,20.1,49.3,94.8,0.8,...,0.0,26.9,0,12128,98308,12596,10175,4,2238.55,3.8
56045,7201,7208,-0.1,7208,6.5,21.6,18.1,47.4,95.0,0.7,...,0.0,29.3,0,11540,64312,9395,7520,1,2398.09,3.0

In [8]:
votes = pd.read_csv("votes.csv")

In [9]:
votes_2016 = votes.set_index("fips")

In [10]:
def dummyvote(row):
    if row['Trump'] > row['Clinton']:
        val = 1
    else:
        val = 0
    return val


votes_2016['Rep2016'] = votes_2016.apply(dummyvote, axis=1)

In [11]:
def dummyvotes(row):
    if row['Romney'] > row['Obama']:
        val = 1
    else:
        val = 0
    return val


votes_2016['Rep2012'] = votes_2016.apply(dummyvotes, axis=1)

In [12]:
votes_2016

,Unnamed: 0,X,votes_dem_2016,votes_gop_2016,total_votes_2016,Clinton,Trump,diff_2016,per_point_diff_2016,state_abbr,...,LND110210,Density,Clinton_Obama,Trump_Romney,Trump_Prediction,Clinton_Prediction,Trump_Deviation,Clinton_Deviation,Rep2016,Rep2012
fips,,,,,,,,,,,,,,,,,,,,,
1001,30,29,5908,18110,24661,0.239569,0.734358,12202,-0.494789,AL,...,594.44,91.8,-0.026189,0.008021,0.620859,0.340493,-0.113499,0.100924,1,1
1003,31,30,18409,72780,94090,0.195653,0.773515,54371,-0.577862,AL,...,1589.78,114.6,-0.020013,-0.000383,0.586749,0.359502,-0.186766,0.163849,1,1
1005,32,31,4848,5431,10390,0.466603,0.522714,583,-0.056112,AL,...,884.88,31.0,-0.045920,0.039339,0.517832,0.474693,-0.004882,0.008090,1,0
1007,33,32,1874,6733,8748,0.214220,0.769662,4859,-0.555441,AL,...,622.58,36.8,-0.047965,0.038998,0.692227,0.286031,-0.077434,0.071811,1,1
1009,34,33,2150,22808,25384,0.084699,0.898519,20658,-0.813820,AL,...,644.78,88.9,-0.038779,0.033590,0.789649,0.177490,-0.108870,0.092791,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56037,3137,3136,3233,12153,16661,0.194046,0.729428,8920,-0.535382,WY,...,10426.65,4.2,-0.090909,0.047219,0.665093,0.272789,-0.064335,0.078743,1,1
56039,3138,3137,7313,3920,12176,0.600608,0.321945,3393,0.278663,WY,...,3995.38,5.3,0.053672,-0.105847,0.425316,0.494972,0.103372,-0.105635,0,0
56041,3139,3138,1202,6154,8053,0.149261,0.764187,4952,-0.614926,WY,...,2081.26,10.1,-0.043333,-0.018139,0.685461,0.256831,-0.078726,0.107570,1,1
56043,3140,3139,532,2911,3715,0.143203,0.783580,2379,-0.640377,WY,...,2238.55,3.8,-0.059814,0.013189,0.632028,0.305111,-0.151552,0.161908,1,1
56045,3141,3140,294,2898,3334,0.088182,0.869226,2604,-0.781044,WY,...,2398.09,3.0,-0.038811,0.020294,0.717167,0.226544,-0.152059,0.138361,1,1

In [13]:
vote_result = votes_2016[["Rep2016","Rep2012"]]

In [14]:
vote_result

       Rep2016  Rep2012
fips
1001         1        1
1003         1        1
1005         1        0
1007         1        1
1009         1        1
...        ...      ...
56037        1        1
56039        0        0
56041        1        1
56043        1        1
56045        1        1

[3112 rows x 2 columns]

In [15]:
merged_data = vote_result.merge(facts_used,how="left",on=["fips"])

In [16]:
merged_data = merged_data.drop(["POP010210","PST040210"], axis=1)

## Split data

In [17]:
y = merged_data["Rep2016"]
X = merged_data.drop(['Rep2016'], axis = 1)

In [18]:
x_in, x_out, y_in, y_out = train_test_split(X, y, test_size=0.25)

In [19]:
x_in

,Rep2012,PST045214,PST120214,AGE135214,AGE295214,AGE775214,SEX255214,RHI125214,RHI225214,RHI325214,...,SBO415207,SBO015207,MAN450207,WTN220207,RTN130207,RTN131207,AFN120207,BPS030214,LND110210,POP060210
fips,,,,,,,,,,,,,,,,,,,,,
22027,1,16412,-4.6,5.3,18.4,17.5,43.4,46.6,50.9,0.5,...,0.0,30.1,0,125891,74200,4516,2251,0,754.88,22.8
26091,1,99047,-0.8,5.6,21.9,16.8,49.4,94.1,2.8,0.6,...,0.0,27.3,2230840,451920,944698,9336,94196,92,749.56,133.3
22053,1,31477,-0.4,7.2,25.9,15.2,51.1,79.9,17.1,0.7,...,0.0,28.4,189206,0,338794,10916,26709,89,651.33,48.5
53007,1,74588,2.9,6.8,24.2,17.5,50.1,93.8,0.8,1.8,...,0.0,25.8,0,788345,1022020,14460,171201,304,2920.53,24.8
29033,1,9043,-2.7,6.2,22.7,20.6,50.8,95.5,2.1,0.3,...,0.0,36.3,0,70062,60608,6161,5499,11,694.62,13.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46129,1,5511,1.3,6.0,22.6,24.3,51.1,82.3,0.5,13.6,...,0.0,15.2,0,107036,74782,14187,19839,9,708.63,7.7
5091,1,43428,-0.1,7.0,24.1,15.2,50.8,71.7,25.1,0.8,...,0.0,18.9,712872,0,407683,9503,43650,37,625.58,69.5
50011,0,48642,1.9,6.0,23.1,13.9,50.3,95.5,0.7,1.0,...,0.0,23.6,0,413283,545346,11383,39606,152,633.71,75.3
19061,0,96370,2.9,6.1,23.1,16.2,50.6,93.7,3.0,0.2,...,0.0,21.7,4711245,1847726,1433461,15538,145685,276,608.31,154.0
56011,1,7248,2.3,6.6,23.5,18.0,49.5,96.3,1.1,0.9,...,0.0,16.8,0,14112,56351,8842,6135,5,2854.41,2.5

In [20]:
x_scaled = preprocessing.scale(x_in)

In [21]:
x_out_scaled = preprocessing.scale(x_out)

In [22]:
target_names =  ["Rep Lose","Rep Win"]

## Predict voting result:

## Logist

In [23]:
grid={ 'C': [0.001,0.01,0.1,1,10,100,1000], "penalty":["l2"], "max_iter":[4000]}
logist=LogisticRegression()
logist_cv=GridSearchCV(logist,grid,cv=10)
logist_cv.fit(x_scaled,y_in)

print("tuned hpyerparameters :(best parameters) ",logist_cv.best_params_)
print("accuracy :",logist_cv.best_score_)

tuned hpyerparameters :(best parameters)  {'C': 0.1, 'max_iter': 4000, 'penalty': 'l2'}
accuracy : 0.9618686034995048

In [24]:
y_logit_pred = logist_cv.predict(x_out_scaled)
print(classification_report(y_out, y_logit_pred, target_names=target_names))

              precision    recall  f1-score   support

    Rep Lose       0.87      0.87      0.87       119
     Rep Win       0.98      0.98      0.98       659

    accuracy                           0.96       778
   macro avg       0.92      0.92      0.92       778
weighted avg       0.96      0.96      0.96       778

## Nearest Neighbor

In [25]:
grid={ 'n_neighbors': [1,3,7,9,11,13,15], "weights":["uniform","distance"], "metric":["euclidean","manhattan"]}
knn = KNeighborsClassifier()
knn_cv = GridSearchCV(knn,grid,cv=10)
knn_cv.fit(x_scaled,y_in)

print("tuned hpyerparameters :(best parameters) ",knn_cv.best_params_)
print("accuracy :",knn_cv.best_score_)

tuned hpyerparameters :(best parameters)  {'metric': 'euclidean', 'n_neighbors': 13, 'weights': 'distance'}
accuracy : 0.951571842558967

In [26]:
y_KNN_pred = knn_cv.predict(x_out_scaled)
print(classification_report(y_out, y_KNN_pred, target_names=target_names))

              precision    recall  f1-score   support

    Rep Lose       0.84      0.77      0.81       119
     Rep Win       0.96      0.97      0.97       659

    accuracy                           0.94       778
   macro avg       0.90      0.87      0.89       778
weighted avg       0.94      0.94      0.94       778

## Decision Tree

In [27]:
grid = {"criterion" : ["gini","entropy"] , "max_depth":[2,4,6,8,10] , "min_samples_split":[2,4,6,8,10] , "min_samples_leaf":[2,4,6,8,10]}
dt = tree.DecisionTreeClassifier()
dt_cv = GridSearchCV(dt,grid,cv=10)
dt_cv.fit(x_scaled,y_in)

print("tuned hpyerparameters :(best parameters) ",dt_cv.best_params_)
print("accuracy :",dt_cv.best_score_)

tuned hpyerparameters :(best parameters)  {'criterion': 'entropy', 'max_depth': 10, 'min_samples_leaf': 10, 'min_samples_split': 8}
accuracy : 0.9545834708924839

In [28]:
y_DT_pred = dt_cv.predict(x_out_scaled)
print(classification_report(y_out, y_DT_pred, target_names=target_names))

              precision    recall  f1-score   support

    Rep Lose       0.82      0.89      0.85       119
     Rep Win       0.98      0.97      0.97       659

    accuracy                           0.95       778
   macro avg       0.90      0.93      0.91       778
weighted avg       0.96      0.95      0.95       778

## Swing Countis
try to predict swing counties

In [29]:
def swingvotes(row):
    if row['Rep2016'] > row['Rep2012']:
        val = 2
    elif row['Rep2016'] < row['Rep2012']:
        val = 1
    else:
        val = 0
    return val


vote_result['Swingvote'] = vote_result.apply(swingvotes, axis=1)

<ipython-input-29-a915d455242b>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vote_result['Swingvote'] = vote_result.apply(swingvotes, axis=1)

In [30]:
vote_result

       Rep2016  Rep2012  Swingvote
fips
1001         1        1          0
1003         1        1          0
1005         1        0          2
1007         1        1          0
1009         1        1          0
...        ...      ...        ...
56037        1        1          0
56039        0        0          0
56041        1        1          0
56043        1        1          0
56045        1        1          0

[3112 rows x 3 columns]

In [56]:
vote_result.groupby('Swingvote').count()

           Rep2016  Rep2012
Swingvote
0             2874     2874
1               20       20
2              218      218

In [57]:
y = vote_result['Swingvote']
X = merged_data.drop(["Rep2016"], axis = 1)

In [58]:
x_in, x_out, y_in, y_out = train_test_split(X, y, test_size=0.3)

In [59]:
x_scaled = preprocessing.scale(x_in)
x_out_scaled = preprocessing.scale(x_out)

## logist

In [60]:
logist_cv.fit(x_scaled,y_in)
print("tuned hpyerparameters :(best parameters) ",logist_cv.best_params_)
print("accuracy :",logist_cv.best_score_)

tuned hpyerparameters :(best parameters)  {'C': 0.1, 'max_iter': 4000, 'penalty': 'l2'}
accuracy : 0.9664862808100452

In [61]:
y_logit_pred = logist_cv.predict(x_out_scaled)
print(classification_report(y_out, y_logit_pred))

              precision    recall  f1-score   support

           0       0.96      0.98      0.97       865
           1       0.00      0.00      0.00         8
           2       0.72      0.56      0.63        61

    accuracy                           0.95       934
   macro avg       0.56      0.51      0.53       934
weighted avg       0.94      0.95      0.94       934

## KNN

In [62]:
knn_cv.fit(x_scaled,y_in)
print("tuned hpyerparameters :(best parameters) ",knn_cv.best_params_)
print("accuracy :",knn_cv.best_score_)

tuned hpyerparameters :(best parameters)  {'metric': 'euclidean', 'n_neighbors': 13, 'weights': 'uniform'}
accuracy : 0.963273157738976

In [63]:
y_KNN_pred = knn_cv.predict(x_out_scaled)
print(classification_report(y_out, y_KNN_pred))

              precision    recall  f1-score   support

           0       0.96      0.98      0.97       865
           1       0.00      0.00      0.00         8
           2       0.73      0.57      0.64        61

    accuracy                           0.95       934
   macro avg       0.56      0.52      0.54       934
weighted avg       0.94      0.95      0.94       934

/opt/network/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

## DT

In [64]:
dt_cv.fit(x_scaled,y_in)
print("tuned hpyerparameters :(best parameters) ",dt_cv.best_params_)
print("accuracy :",dt_cv.best_score_)

tuned hpyerparameters :(best parameters)  {'criterion': 'gini', 'max_depth': 4, 'min_samples_leaf': 10, 'min_samples_split': 10}
accuracy : 0.9641927028283938

In [65]:
y_DT_pred = dt_cv.predict(x_out_scaled)
print(classification_report(y_out, y_DT_pred))

              precision    recall  f1-score   support

           0       0.97      0.98      0.98       865
           1       0.00      0.00      0.00         8
           2       0.73      0.67      0.70        61

    accuracy                           0.95       934
   macro avg       0.57      0.55      0.56       934
weighted avg       0.94      0.95      0.95       934

/opt/network/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))