In [113]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.svm import SVC
import statsmodels.api as sm
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier, plot_tree

## Data Cleaning

In [114]:
countywithnames = pd.read_csv("county_facts.csv")

In [115]:
countywithnames.dropna(inplace=True)

In [116]:
county_facts = countywithnames.set_index("fips")

In [117]:
county_facts

,area_name,state_abbreviation,PST045214,PST040210,PST120214,POP010210,AGE135214,AGE295214,AGE775214,SEX255214,...,SBO415207,SBO015207,MAN450207,WTN220207,RTN130207,RTN131207,AFN120207,BPS030214,LND110210,POP060210
fips,,,,,,,,,,,,,,,,,,,,,
1001,Autauga County,AL,55395,54571,1.5,54571,6.0,25.2,13.8,51.4,...,0.7,31.7,0,0,598175,12003,88157,131,594.44,91.8
1003,Baldwin County,AL,200111,182265,9.8,182265,5.6,22.2,18.7,51.2,...,1.3,27.3,1410273,0,2966489,17166,436955,1384,1589.78,114.6
1005,Barbour County,AL,26887,27457,-2.1,27457,5.7,21.2,16.5,46.6,...,0.0,27.0,0,0,188337,6334,0,8,884.88,31.0
1007,Bibb County,AL,22506,22919,-1.8,22915,5.3,21.0,14.8,45.9,...,0.0,0.0,0,0,124707,5804,10757,19,622.58,36.8
1009,Blount County,AL,57719,57322,0.7,57322,6.1,23.6,17.0,50.5,...,0.0,23.2,341544,0,319700,5622,20941,3,644.78,88.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56037,Sweetwater County,WY,45010,43806,2.7,43806,7.3,27.0,9.5,48.1,...,3.8,27.2,0,437493,898189,22843,150439,227,10426.65,4.2
56039,Teton County,WY,22930,21294,7.7,21294,5.7,19.1,12.2,48.2,...,3.3,25.3,0,0,515644,25688,327363,145,3995.38,5.3
56041,Uinta County,WY,20904,21118,-1.0,21118,7.6,29.8,11.0,49.6,...,2.2,15.9,0,159375,413983,20626,35497,40,2081.26,10.1
56043,Washakie County,WY,8322,8533,-2.5,8533,5.5,23.9,20.1,49.3,...,0.0,26.9,0,12128,98308,12596,10175,4,2238.55,3.8
56045,Weston County,WY,7201,7208,-0.1,7208,6.5,21.6,18.1,47.4,...,0.0,29.3,0,11540,64312,9395,7520,1,2398.09,3.0

In [118]:
facts_used = county_facts.drop(['area_name', 'state_abbreviation'], axis = 1)

In [119]:
facts_used

,PST045214,PST040210,PST120214,POP010210,AGE135214,AGE295214,AGE775214,SEX255214,RHI125214,RHI225214,...,SBO415207,SBO015207,MAN450207,WTN220207,RTN130207,RTN131207,AFN120207,BPS030214,LND110210,POP060210
fips,,,,,,,,,,,,,,,,,,,,,
1001,55395,54571,1.5,54571,6.0,25.2,13.8,51.4,77.9,18.7,...,0.7,31.7,0,0,598175,12003,88157,131,594.44,91.8
1003,200111,182265,9.8,182265,5.6,22.2,18.7,51.2,87.1,9.6,...,1.3,27.3,1410273,0,2966489,17166,436955,1384,1589.78,114.6
1005,26887,27457,-2.1,27457,5.7,21.2,16.5,46.6,50.2,47.6,...,0.0,27.0,0,0,188337,6334,0,8,884.88,31.0
1007,22506,22919,-1.8,22915,5.3,21.0,14.8,45.9,76.3,22.1,...,0.0,0.0,0,0,124707,5804,10757,19,622.58,36.8
1009,57719,57322,0.7,57322,6.1,23.6,17.0,50.5,96.0,1.8,...,0.0,23.2,341544,0,319700,5622,20941,3,644.78,88.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56037,45010,43806,2.7,43806,7.3,27.0,9.5,48.1,94.3,1.5,...,3.8,27.2,0,437493,898189,22843,150439,227,10426.65,4.2
56039,22930,21294,7.7,21294,5.7,19.1,12.2,48.2,94.9,1.2,...,3.3,25.3,0,0,515644,25688,327363,145,3995.38,5.3
56041,20904,21118,-1.0,21118,7.6,29.8,11.0,49.6,95.4,0.9,...,2.2,15.9,0,159375,413983,20626,35497,40,2081.26,10.1
56043,8322,8533,-2.5,8533,5.5,23.9,20.1,49.3,94.8,0.8,...,0.0,26.9,0,12128,98308,12596,10175,4,2238.55,3.8
56045,7201,7208,-0.1,7208,6.5,21.6,18.1,47.4,95.0,0.7,...,0.0,29.3,0,11540,64312,9395,7520,1,2398.09,3.0

In [120]:
votes = pd.read_csv("votes.csv")

In [121]:
fips = votes["fips"]

In [122]:
votes_2016 = votes.set_index("fips")

In [123]:
def dummyvote(row):
    if row['Trump'] > row['Clinton']:
        val = 1
    else:
        val = 0
    return val


votes_2016['Rep2016'] = votes_2016.apply(dummyvote, axis=1)

In [124]:
def dummyvotes(row):
    if row['Romney'] > row['Obama']:
        val = 1
    else:
        val = 0
    return val


votes_2016['Rep2012'] = votes_2016.apply(dummyvotes, axis=1)

In [125]:
votes_2016

,Unnamed: 0,X,votes_dem_2016,votes_gop_2016,total_votes_2016,Clinton,Trump,diff_2016,per_point_diff_2016,state_abbr,...,LND110210,Density,Clinton_Obama,Trump_Romney,Trump_Prediction,Clinton_Prediction,Trump_Deviation,Clinton_Deviation,Rep2016,Rep2012
fips,,,,,,,,,,,,,,,,,,,,,
1001,30,29,5908,18110,24661,0.239569,0.734358,12202,-0.494789,AL,...,594.44,91.8,-0.026189,0.008021,0.620859,0.340493,-0.113499,0.100924,1,1
1003,31,30,18409,72780,94090,0.195653,0.773515,54371,-0.577862,AL,...,1589.78,114.6,-0.020013,-0.000383,0.586749,0.359502,-0.186766,0.163849,1,1
1005,32,31,4848,5431,10390,0.466603,0.522714,583,-0.056112,AL,...,884.88,31.0,-0.045920,0.039339,0.517832,0.474693,-0.004882,0.008090,1,0
1007,33,32,1874,6733,8748,0.214220,0.769662,4859,-0.555441,AL,...,622.58,36.8,-0.047965,0.038998,0.692227,0.286031,-0.077434,0.071811,1,1
1009,34,33,2150,22808,25384,0.084699,0.898519,20658,-0.813820,AL,...,644.78,88.9,-0.038779,0.033590,0.789649,0.177490,-0.108870,0.092791,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56037,3137,3136,3233,12153,16661,0.194046,0.729428,8920,-0.535382,WY,...,10426.65,4.2,-0.090909,0.047219,0.665093,0.272789,-0.064335,0.078743,1,1
56039,3138,3137,7313,3920,12176,0.600608,0.321945,3393,0.278663,WY,...,3995.38,5.3,0.053672,-0.105847,0.425316,0.494972,0.103372,-0.105635,0,0
56041,3139,3138,1202,6154,8053,0.149261,0.764187,4952,-0.614926,WY,...,2081.26,10.1,-0.043333,-0.018139,0.685461,0.256831,-0.078726,0.107570,1,1
56043,3140,3139,532,2911,3715,0.143203,0.783580,2379,-0.640377,WY,...,2238.55,3.8,-0.059814,0.013189,0.632028,0.305111,-0.151552,0.161908,1,1
56045,3141,3140,294,2898,3334,0.088182,0.869226,2604,-0.781044,WY,...,2398.09,3.0,-0.038811,0.020294,0.717167,0.226544,-0.152059,0.138361,1,1

In [126]:
vote_result = votes_2016[["Rep2016","Rep2012"]]

In [127]:
vote_result

       Rep2016  Rep2012
fips
1001         1        1
1003         1        1
1005         1        0
1007         1        1
1009         1        1
...        ...      ...
56037        1        1
56039        0        0
56041        1        1
56043        1        1
56045        1        1

[3112 rows x 2 columns]

In [128]:
merged_data = vote_result.merge(facts_used,how="left",on=["fips"])

In [129]:
merged_data = merged_data.drop(["POP010210","PST040210"], axis=1)

In [130]:
merged_data

,Rep2016,Rep2012,PST045214,PST120214,AGE135214,AGE295214,AGE775214,SEX255214,RHI125214,RHI225214,...,SBO415207,SBO015207,MAN450207,WTN220207,RTN130207,RTN131207,AFN120207,BPS030214,LND110210,POP060210
fips,,,,,,,,,,,,,,,,,,,,,
1001,1,1,55395,1.5,6.0,25.2,13.8,51.4,77.9,18.7,...,0.7,31.7,0,0,598175,12003,88157,131,594.44,91.8
1003,1,1,200111,9.8,5.6,22.2,18.7,51.2,87.1,9.6,...,1.3,27.3,1410273,0,2966489,17166,436955,1384,1589.78,114.6
1005,1,0,26887,-2.1,5.7,21.2,16.5,46.6,50.2,47.6,...,0.0,27.0,0,0,188337,6334,0,8,884.88,31.0
1007,1,1,22506,-1.8,5.3,21.0,14.8,45.9,76.3,22.1,...,0.0,0.0,0,0,124707,5804,10757,19,622.58,36.8
1009,1,1,57719,0.7,6.1,23.6,17.0,50.5,96.0,1.8,...,0.0,23.2,341544,0,319700,5622,20941,3,644.78,88.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56037,1,1,45010,2.7,7.3,27.0,9.5,48.1,94.3,1.5,...,3.8,27.2,0,437493,898189,22843,150439,227,10426.65,4.2
56039,0,0,22930,7.7,5.7,19.1,12.2,48.2,94.9,1.2,...,3.3,25.3,0,0,515644,25688,327363,145,3995.38,5.3
56041,1,1,20904,-1.0,7.6,29.8,11.0,49.6,95.4,0.9,...,2.2,15.9,0,159375,413983,20626,35497,40,2081.26,10.1
56043,1,1,8322,-2.5,5.5,23.9,20.1,49.3,94.8,0.8,...,0.0,26.9,0,12128,98308,12596,10175,4,2238.55,3.8
56045,1,1,7201,-0.1,6.5,21.6,18.1,47.4,95.0,0.7,...,0.0,29.3,0,11540,64312,9395,7520,1,2398.09,3.0

## Split data

In [131]:
y = merged_data["Rep2016"]
X = merged_data.drop(['Rep2016'], axis = 1)

In [132]:
x_in, x_out, y_in, y_out = train_test_split(X, y, test_size=0.25)

In [133]:
x_in

,Rep2012,PST045214,PST120214,AGE135214,AGE295214,AGE775214,SEX255214,RHI125214,RHI225214,RHI325214,...,SBO415207,SBO015207,MAN450207,WTN220207,RTN130207,RTN131207,AFN120207,BPS030214,LND110210,POP060210
fips,,,,,,,,,,,,,,,,,,,,,
48497,1,61638,4.2,6.5,25.1,14.4,49.6,95.3,1.6,1.0,...,5.1,23.4,376535,418384,565279,9819,59273,46,904.42,65.4
19149,1,24874,-0.4,5.9,25.1,17.6,50.3,97.2,0.5,0.5,...,0.0,0.0,0,243010,299650,12330,21970,37,862.89,29.0
49033,1,2293,1.3,7.0,29.7,17.7,48.7,97.6,0.3,0.8,...,0.0,0.0,0,0,11499,5601,3732,21,1028.78,2.2
8093,1,16345,0.9,3.7,16.7,16.2,47.3,94.6,0.6,1.3,...,0.0,28.0,0,3435,55409,3266,11083,88,2193.85,7.4
8113,0,7840,6.5,4.7,18.9,10.4,46.9,95.3,0.7,1.4,...,3.1,23.3,0,0,97815,13114,77135,36,1286.61,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29199,1,4863,0.4,8.3,28.3,18.9,50.7,98.5,0.1,0.3,...,0.0,0.0,0,0,39408,8205,2216,1,436.67,11.1
45011,0,21959,-2.9,7.0,25.3,15.9,52.3,53.1,44.1,0.6,...,0.0,32.9,681251,0,169135,7361,14706,37,548.39,41.2
27041,1,36790,2.2,5.4,21.1,21.6,50.0,97.7,0.5,0.4,...,0.0,13.5,688179,0,625509,17390,71018,184,637.30,56.5
46137,0,2826,0.9,6.3,35.7,6.7,49.0,24.4,0.3,71.2,...,0.0,0.0,0,0,0,0,0,0,1961.27,1.4
5065,1,13486,-1.5,4.5,18.2,25.0,47.6,95.4,1.8,1.1,...,0.0,0.0,0,0,104699,8035,3275,3,580.58,23.6

In [134]:
x_scaled = preprocessing.scale(x_in)

In [135]:
x_out_scaled = preprocessing.scale(x_out)

In [136]:
target_names =  ["Rep Lose","Rep Win"]

In [137]:
X_scaled = preprocessing.scale(X)

## Predict voting result:

## Logist

In [138]:
grid={ 'C': [0.001,0.01,0.1,1,10,100,1000], "penalty":["l2"], "max_iter":[4000]}
logist=LogisticRegression()
logist_cv=GridSearchCV(logist,grid,cv=10)
logist_cv.fit(x_scaled,y_in)

print("tuned hpyerparameters :(best parameters) ",logist_cv.best_params_)
print("accuracy :",logist_cv.best_score_)

tuned hpyerparameters :(best parameters)  {'C': 0.01, 'max_iter': 4000, 'penalty': 'l2'}
accuracy : 0.9618667693774989

In [139]:
y_logit_pred = logist_cv.predict(x_out_scaled)
print(classification_report(y_out, y_logit_pred, target_names=target_names))

              precision    recall  f1-score   support

    Rep Lose       0.88      0.84      0.86       116
     Rep Win       0.97      0.98      0.98       662

    accuracy                           0.96       778
   macro avg       0.93      0.91      0.92       778
weighted avg       0.96      0.96      0.96       778

In [140]:
y_result = logist_cv.predict(X_scaled)

In [141]:
y_result

array([1, 1, 0, ..., 1, 1, 1])

In [142]:
y_result = pd.DataFrame({'Rep2016': y_result})

In [143]:
y_result["Predict"] = y_result["Rep2016"]

In [144]:
y_result = y_result.drop(["Rep2016"],axis=1)

In [145]:
fips = pd.DataFrame(fips)

In [112]:
logitpredict_result = y_result.merge(fips, right_index=True, left_index=True)

In [78]:
logitpredict_result

      Predict   fips
0           1   1001
1           1   1003
2           0   1005
3           1   1007
4           1   1009
...       ...    ...
3107        1  56037
3108        0  56039
3109        1  56041
3110        1  56043
3111        1  56045

[3112 rows x 2 columns]

## Nearest Neighbor

In [27]:
grid={ 'n_neighbors': [1,3,7,9,11,13,15], "weights":["uniform","distance"], "metric":["euclidean","manhattan"]}
knn = KNeighborsClassifier()
knn_cv = GridSearchCV(knn,grid,cv=10)
knn_cv.fit(x_scaled,y_in)

print("tuned hpyerparameters :(best parameters) ",knn_cv.best_params_)
print("accuracy :",knn_cv.best_score_)

tuned hpyerparameters :(best parameters)  {'metric': 'euclidean', 'n_neighbors': 7, 'weights': 'uniform'}
accuracy : 0.9477311910788305

In [28]:
y_KNN_pred = knn_cv.predict(x_out_scaled)
print(classification_report(y_out, y_KNN_pred, target_names=target_names))

              precision    recall  f1-score   support

    Rep Lose       0.88      0.78      0.83       117
     Rep Win       0.96      0.98      0.97       661

    accuracy                           0.95       778
   macro avg       0.92      0.88      0.90       778
weighted avg       0.95      0.95      0.95       778

## Decision Tree

In [29]:
grid = {"criterion" : ["gini","entropy"] , "max_depth":[2,4,6,8,10] , "min_samples_split":[2,4,6,8,10] , "min_samples_leaf":[2,4,6,8,10]}
dt = tree.DecisionTreeClassifier()
dt_cv = GridSearchCV(dt,grid,cv=10)
dt_cv.fit(x_scaled,y_in)

print("tuned hpyerparameters :(best parameters) ",dt_cv.best_params_)
print("accuracy :",dt_cv.best_score_)

tuned hpyerparameters :(best parameters)  {'criterion': 'gini', 'max_depth': 6, 'min_samples_leaf': 10, 'min_samples_split': 6}
accuracy : 0.9558673562965408

In [30]:
y_DT_pred = dt_cv.predict(x_out_scaled)
print(classification_report(y_out, y_DT_pred, target_names=target_names))

              precision    recall  f1-score   support

    Rep Lose       0.90      0.85      0.88       117
     Rep Win       0.97      0.98      0.98       661

    accuracy                           0.96       778
   macro avg       0.94      0.92      0.93       778
weighted avg       0.96      0.96      0.96       778

## Swing Countis
try to predict swing counties

In [31]:
def swingvotes(row):
    if row['Rep2016'] != row['Rep2012']:
        val = 1
    else:
        val = 0
    return val


vote_result['Swingvote'] = vote_result.apply(swingvotes, axis=1)

<ipython-input-31-5f023ba276b8>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vote_result['Swingvote'] = vote_result.apply(swingvotes, axis=1)

In [32]:
vote_result

       Rep2016  Rep2012  Swingvote
fips
1001         1        1          0
1003         1        1          0
1005         1        0          1
1007         1        1          0
1009         1        1          0
...        ...      ...        ...
56037        1        1          0
56039        0        0          0
56041        1        1          0
56043        1        1          0
56045        1        1          0

[3112 rows x 3 columns]

In [ ]:
vote_result.append

In [33]:
y = vote_result['Swingvote']
X = merged_data.drop(["Rep2016"], axis = 1)

In [34]:
x_in, x_out, y_in, y_out = train_test_split(X, y, test_size=0.3)

In [35]:
x_scaled = preprocessing.scale(x_in)
x_out_scaled = preprocessing.scale(x_out)

## logist

In [36]:
logist_cv.fit(x_scaled,y_in)
print("tuned hpyerparameters :(best parameters) ",logist_cv.best_params_)
print("accuracy :",logist_cv.best_score_)

tuned hpyerparameters :(best parameters)  {'C': 0.1, 'max_iter': 4000, 'penalty': 'l2'}
accuracy : 0.9568426838033229

In [37]:
y_logit_pred = logist_cv.predict(x_out_scaled)
print(classification_report(y_out, y_logit_pred, target_names= ["No Change", "Vote Change"]))

              precision    recall  f1-score   support

   No Change       0.93      1.00      0.96       845
 Vote Change       0.88      0.34      0.49        89

    accuracy                           0.93       934
   macro avg       0.91      0.67      0.73       934
weighted avg       0.93      0.93      0.92       934

## KNN

In [38]:
knn_cv.fit(x_scaled,y_in)
print("tuned hpyerparameters :(best parameters) ",knn_cv.best_params_)
print("accuracy :",knn_cv.best_score_)

tuned hpyerparameters :(best parameters)  {'metric': 'euclidean', 'n_neighbors': 15, 'weights': 'uniform'}
accuracy : 0.9577601149959836

In [39]:
y_KNN_pred = knn_cv.predict(x_out_scaled)
print(classification_report(y_out, y_KNN_pred, target_names= ["No Change", "Vote Change"]))

              precision    recall  f1-score   support

   No Change       0.95      0.99      0.97       845
 Vote Change       0.84      0.53      0.65        89

    accuracy                           0.95       934
   macro avg       0.90      0.76      0.81       934
weighted avg       0.94      0.95      0.94       934

## DT

In [40]:
dt_cv.fit(x_scaled,y_in)
print("tuned hpyerparameters :(best parameters) ",dt_cv.best_params_)
print("accuracy :",dt_cv.best_score_)

tuned hpyerparameters :(best parameters)  {'criterion': 'entropy', 'max_depth': 6, 'min_samples_leaf': 10, 'min_samples_split': 4}
accuracy : 0.9600515790808777

In [41]:
y_DT_pred = dt_cv.predict(x_out_scaled)
print(classification_report(y_out, y_DT_pred, target_names=["No Change", "Vote Change"]))

              precision    recall  f1-score   support

   No Change       0.96      0.98      0.97       845
 Vote Change       0.79      0.64      0.71        89

    accuracy                           0.95       934
   macro avg       0.88      0.81      0.84       934
weighted avg       0.95      0.95      0.95       934